FROM maven:3.3.3-jdk-8

# use --build-arg option to pass system proxy name and port
ARG PROXY_HOST
ARG PROXY_PORT

ENV GAIA_HOME=/usr/local/gaia

RUN mkdir -p $GAIA_HOME
WORKDIR $GAIA_HOME

ADD . $GAIA_HOME

RUN ["mvn","clean","install"]

# get all the downloads out of the way
RUN if [ -z "$PROXY_HOST" ]; then \
      mvn clean install ; \
    else \
      mvn -DuseProxy=true -DproxyHost=$PROXY_HOST -DproxyPort=$PROXY_PORT clean install ; \
    fi
